name: Run JSONPlaceholder Test
on:
  push:
    branches:
      - workflows
  pull_request:
    branches:
      - workflows
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Add node
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm ci
      - name: Run JSONPlaceholder Test
        run: npm run run_JSONPlaceholder_test
